export const tableOption = {
  border: true,
  index: true,
  indexLabel: '序号',
  stripe: true,
  menuAlign: 'center',
  align: 'center',
  searchMenuSpan: 6,
  viewBtn: true,
  addBtn: true,
  editBtn: true,
  height: 'calc(100vh - 211px)',
  column: [{
    label: '系统配置',
    prop: 'id',
    align: 'center',
    width: 160
  }, {
    width: '200px',
    label: '业务领域',
    prop: 'lookupDomain',
    align: 'center'
  }, {
    width: '200px',
    label: '类型',
    prop: 'lookupType',
    align: 'center'
  }, {
    width: '200px',
    label: '编码',
    prop: 'lookupCode',
    align: 'center'
  }, {
    width: '200px',
    label: '值',
    prop: 'lookupValue',
    align: 'center'
  }, {
    width: '200px',
    label: '说明',
    prop: 'lookupComment',
    align: 'center'
  }, {
    width: '200px',
    label: '显示顺序',
    prop: 'lookupOrder',
    align: 'center'
  }, {
    width: '200px',
    label: '扩展字段1',
    prop: 'attribute1',
    align: 'center'
  }, {
    width: '200px',
    label: '扩展字段2',
    prop: 'attribute2',
    align: 'center'
  }, {
    width: '200px',
    label: '扩展字段3',
    prop: 'attribute3',
    align: 'center'
  }, {
    width: '200px',
    label: '扩展字段4',
    prop: 'attribute4',
    align: 'center'
  }, {
    width: '200px',
    label: '扩展字段5',
    prop: 'attribute5',
    align: 'center'
  }, {
    width: '200px',
    label: '扩展字段6',
    prop: 'attribute6',
    align: 'center'
  },
  {
    width: '200px',
    label: '详细信息',
    prop: 'content',
    align: 'center'
  }, {
    label: '创建人ID',
    prop: 'createBy',
    align: 'center'
  }, {
    width: '150px',
    label: '创建时间',
    prop: 'createTime',
    type: 'date',
    format: 'yyyy-MM-dd hh:mm:ss',
    align: 'center'
  }, {
    label: '更新人ID',
    prop: 'updateBy',
    align: 'center'
  }, {
    width: '150px',
    label: '更新时间',
    prop: 'updateTime',
    type: 'date',
    format: 'yyyy-MM-dd hh:mm:ss',
    align: 'center'
  }, {
    label: '版本号',
    prop: 'version',
    align: 'center'
  }]
}
