export const tableOption = {
  border: true,
  index: true,
  indexLabel: '序号',
  size: 'mini',
  stripe: true,
  menuAlign: 'center',
  align: 'center',
  searchMenuSpan: 6,
  viewBtn: true,
  addBtn: true,
  editBtn: true,
  height: 'calc(100vh - 211px)',
  column: [{
    label: '组织ID',
    prop: 'id',
    align: 'center'
  }, {
    width: '200px',
    label: '组织编码',
    prop: 'orgCode',
    align: 'center'
  }, {
    width: '200px',
    label: '组织名称',
    prop: 'orgName',
    align: 'center'
  }, {
    width: '200px',
    label: '排序',
    prop: 'orgOrder',
    align: 'center'
  }, {
    width: '200px',
    label: '父组织编码',
    prop: 'orgParentCode',
    align: 'center'
  }, {
    width: '200px',
    label: '组织路径',
    prop: 'orgPath',
    align: 'center'
  }, {
    width: '200px',
    label: '组织名称路径',
    prop: 'orgNamePath',
    align: 'center'
  }, {
    width: '200px',
    label: '多维组织编码',
    prop: 'mdmCode',
    align: 'center'
  }, {
    width: '200px',
    label: '组织描叙',
    prop: 'orgRemark',
    align: 'center'
  }, {
    width: '200px',
    label: '级别',
    prop: 'orgLevel',
    align: 'center'
  }, {
    label: '创建人ID',
    prop: 'createBy',
    align: 'center'
  }, {
    width: '150px',
    label: '创建时间',
    prop: 'createTime',
    type: 'date',
    format: 'yyyy-MM-dd hh:mm:ss',
    align: 'center'
  }, {
    label: '更新人ID',
    prop: 'updateBy',
    align: 'center'
  }, {
    width: '150px',
    label: '更新时间',
    prop: 'updateTime',
    type: 'date',
    format: 'yyyy-MM-dd hh:mm:ss',
    align: 'center'
  }, {
    label: '版本号',
    prop: 'version',
    align: 'center'
  }]
}
